// src/components/reports/shell/ReportFooter.tsx

interface ReportFooterProps {
  generatedAt: string;
  accountLabel: string;
  reportId: string;
}

export function ReportFooter({ generatedAt, accountLabel, reportId }: ReportFooterProps) {
  return (
    <div className="rounded-b-2xl border-t border-border bg-muted/40 px-6 py-3 print:py-2 print:break-inside-avoid">
      <div className="flex flex-wrap items-center justify-between gap-2 text-[10px] text-muted-foreground">
        <span>
          Data as of {generatedAt} · Account: {accountLabel} · Generated by StreamBias
        </span>
        <span className="text-center">
          For informational purposes only. Not financial advice.
        </span>
        <span>Report ID: {reportId}</span>
      </div>
    </div>
  );
}
